import type { Metadata } from 'next'
import { Kumbh_Sans } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const kumb = Kumbh_Sans({ weight: ['400', '700'], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kumb.className}>
        <Header />
        <main className='max-w-6xl mx-auto lg:px-12 lg:py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
